{{- if .Values.ingress.enabled -}}
{{- $fullName := include "iam-evaluation.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "iam-evaluation.name" . }}
    chart: {{ template "iam-evaluation.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: comanage.tier.minikube
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-comanage
              servicePort: http
    - host: christminster-idp.tier.minikube
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-christminster-idp
              servicePort: http
{{- end }}
